export const LANGUAGES = [
  "JavaScript",
  "Rust",
  "Python",
  "C++",
  "Java",
  "Shell",
  "Dart",
  "TypeScript",
  "C",
  "Go",
  "CSS",
  "Vue",
  "PHP",
  "C#",
  "Clojure",
  "Assembly",
  "Nunjucks",
  "HTML",
  "Dockerfile",
  "Ruby",
  "Vim script",
  "Jupyter Notebook",
  "Kotlin",
  "Swift",
  "Julia",
  "Markdown",
  "SCSS",
  "Objective-C",
  "TeX",
  "Scala",
  "Makefile",
  "Haskell",
  "Less",
  "V",
  "Batchfile",
];

export const ROUTES = {
  repositories: "/repos",
  oneRepo: "/repos/:owner/:repo",
  home: "/",
  favourites: "/favourites",
};

export const ORDER = [
  "owner",
  "description",
  "language",
  "open_issues_count",
  "private",
  "stargazers_count",
  "archived",
  "disabled",
  "homepage",
  "license",
  "topics",
  "visibility",
  "watchers_count",
];

export const HUMAN_READABLE_KEYS = {
  owner: "Owner",
  description: "Description",
  language: "Language",
  open_issues_count: "Open issues count",
  private: "Private",
  stargazers_count: "Stargazers count",
  archived: "Archived",
  created_at: "Created at",
  disabled: "Disabled",
  homepage: "Homepage",
  license: "License",
  topics: "Topics",
  updated_at: "Updated at",
  visibility: "Visibility",
  watchers_count: "Watchers count",
};
